app/inventory/urls.py
from django.urls import path
from django.views.generic.base import RedirectView
from .greet import greeting
from . import views as inventory_views

app_name = "inventory"

urlpatterns = [
    path("", inventory_views.MainView.as_view(), name="main"),
    path("car/", inventory_views.CarFormView.as_view(), name="car"),
    path(
        "create_car/",  # noqa
        inventory_views.CarCreateView.as_view(),  # noqa
        name="car-create",  # noqa
    ),  # noqa
    path("list_car/", inventory_views.CarListView.as_view(), name="car-list"),
    path(
        "detail_car/<int:pk>",
        inventory_views.CarDetailView.as_view(),
        name="car-detail",
    ),
    path(
        "update_car/<int:pk>",
        inventory_views.CarUpdateView.as_view(),
        name="car-update",
    ),
    path(
        "delete_car/<int:pk>",
        inventory_views.CarDeleteView.as_view(),
        name="car-delete",
    ),
    path("", RedirectView.as_view(url="/inventory")),
    path("fbv", inventory_views.fbv_view, name="fbv"),
    path("greeting/", greeting, name="greeting"),
]

app/inventory/models.py
from django.db import models


# Create your models here.
class Car(models.Model):
    brand = models.CharField(max_length=200)
    model = models.CharField(max_length=200)
    color = models.CharField(max_length=200)
    year = models.IntegerField(default=1900)

    def __str__(self):
        return f"{self.brand} {self.model} {self.year} {self.color}"

    class Meta:
        ordering = ["-year"]


class Inventory(models.Model):
    car = models.ForeignKey(Car, on_delete=models.CASCADE)
    number = models.IntegerField(default=00)

app/inventory/forms.py
from django import forms


class CarForm(forms.Form):
    brand = forms.CharField()
    model = forms.CharField()
    color = forms.CharField()
    year = forms.IntegerField()

    def do_action(self):
        print("액션을 하였습니당.")

app/inventory/views.py
from django.http import HttpResponse
from django.views import View
from django.views.generic import TemplateView, FormView, CreateView
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import UpdateView, DeleteView
from django.urls import reverse_lazy
from django.utils import timezone
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render
from django.contrib.auth.decorators import login_required

from inventory.models import Car
from inventory.forms import CarForm


@login_required
def fbv_view(request):
    context = {"name": "JaeHyunL"}
    return render(request, "inventory/fbv.html", context)


# 이러한 방식을 CBV Class Based View라고 한다.
class MainView(TemplateView):
    template_name = "inventory/main.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["name"] = "Hello, World!"
        return context


class CarFormView(FormView):
    template_name = "inventory/car_basic_form.html"
    form_class = CarForm

    # Class Base Viedw 에선 evluated가 함수를 import할 때 로드 됨
    # 따라서 아래처럼 쓰거나 lazy_reverse를 써서 로딩할 것.
    success_url = "/inventory"


class CarCreateView(CreateView):
    model = Car
    fields = ["brand", "model", "color", "year"]
    success_url = reverse_lazy("inventory:main")
    # template_name = "inventory/car_basic_form.html"

    def form_valid(self, form):
        print(form.cleaned_data)
        return super().form_valid(form)


class CarListView(LoginRequiredMixin, ListView):
    model = Car
    paginate_by = 100

    queryset = Car.objects.all()

    def get_context_data(self, **kwargs: reverse_lazy) -> dict[str, any]:
        context = super().get_context_data(**kwargs)
        context["now"] = timezone.now()
        return context


class CarDetailView(DetailView):
    model = Car


class CarUpdateView(UpdateView):
    model = Car
    fields = ["brand", "model", "color", "year"]
    template_name_suffix = "_update_form"
    success_url = reverse_lazy("inventory:car-list")


class CarDeleteView(DeleteView):
    model = Car
    success_url = reverse_lazy("inventory:car-list")
    template_name_suffix = "_confirm_delete"

app/inventory/templates/inventory/car_basic_form.html
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Send Message" />
</form>

app/inventory/templates/inventory/car_confirm_delete.html
<form method="post">
    {% csrf_token %}
    <p> {{object}} 진짜 지울꺼야?  </p>
    {{ form.as_div }}
    <input type="submit" value="Confirm">
</form>

app/inventory/templates/inventory/car_create_form.html
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Send Message" />
</form>

app/inventory/templates/inventory/car_detail.html
<h1> {{object.brand}} </h1>
<p> {{object.model}} </p> 
<p> {{object.color}} </p>
<p> {{object.year}} </p>
<a href="{% url "inventory:car-update" car.id %}">Update</a> <br />
<a href="{% url "inventory:car-delete" car.id %}">Delete</a> <br />

app/inventory/templates/inventory/car_form.html
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Send Message" />
</form>

app/inventory/templates/inventory/car_list.html
<h1>Cars</h1>
<ul>
    {% for car in object_list %}
    <li> <a href="{% url "inventory:car-detail" car.id %}"> {{car.brand}}: {{car.model}} {{car.color}} {{car.year}} <a/> </li>
    {% empty %}
    <li>No cars in the inventory</li>
    {% endfor %}
</ul>

app/inventory/templates/inventory/car_update_form.html
<h1>Update</h1>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Update">
</form>

app/inventory/templates/inventory/main.html
<h1> Wellcom to {{ name }}'s Inventory</h1>